name: moviebot
dependencies:
  - Flask=1.1.2
  - Flask-WTF=0.14.3
  - gunicorn=20.0.4
  - Jinja2=2.11.2
  - joblib=0.17.0
  - numpy
  - scikit-learn=0.23.2
  - scipy
  - threadpoolctl=2.1.0
  - Werkzeug=1.0.1
  - WTForms=2.3.3
